"""resiliencehub base URL and path."""

from .responses import ResilienceHubResponse

url_bases = [
    r"https?://resiliencehub\.(.+)\.amazonaws\.com",
]

url_paths = {
    "{0}/accept-resource-grouping-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/add-draft-app-version-resource-mappings$": ResilienceHubResponse.dispatch,
    "{0}/batch-update-recommendation-status$": ResilienceHubResponse.dispatch,
    "{0}/create-app$": ResilienceHubResponse.dispatch,
    "{0}/create-app-version-app-component$": ResilienceHubResponse.dispatch,
    "{0}/create-app-version-resource$": ResilienceHubResponse.dispatch,
    "{0}/create-recommendation-template$": ResilienceHubResponse.dispatch,
    "{0}/create-resiliency-policy$": ResilienceHubResponse.dispatch,
    "{0}/delete-app$": ResilienceHubResponse.dispatch,
    "{0}/delete-app-assessment$": ResilienceHubResponse.dispatch,
    "{0}/delete-app-input-source$": ResilienceHubResponse.dispatch,
    "{0}/delete-app-version-app-component$": ResilienceHubResponse.dispatch,
    "{0}/delete-app-version-resource$": ResilienceHubResponse.dispatch,
    "{0}/delete-recommendation-template$": ResilienceHubResponse.dispatch,
    "{0}/delete-resiliency-policy$": ResilienceHubResponse.dispatch,
    "{0}/describe-app$": ResilienceHubResponse.dispatch,
    "{0}/describe-app-assessment$": ResilienceHubResponse.dispatch,
    "{0}/describe-app-version$": ResilienceHubResponse.dispatch,
    "{0}/describe-app-version-app-component$": ResilienceHubResponse.dispatch,
    "{0}/describe-app-version-resource$": ResilienceHubResponse.dispatch,
    "{0}/describe-app-version-resources-resolution-status$": ResilienceHubResponse.dispatch,
    "{0}/describe-app-version-template$": ResilienceHubResponse.dispatch,
    "{0}/describe-draft-app-version-resources-import-status$": ResilienceHubResponse.dispatch,
    "{0}/describe-metrics-export$": ResilienceHubResponse.dispatch,
    "{0}/describe-resource-grouping-recommendation-task$": ResilienceHubResponse.dispatch,
    "{0}/describe-resiliency-policy$": ResilienceHubResponse.dispatch,
    "{0}/import-resources-to-draft-app-version$": ResilienceHubResponse.dispatch,
    "{0}/list-alarm-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/list-app-assessment-compliance-drifts$": ResilienceHubResponse.dispatch,
    "{0}/list-app-assessment-resource-drifts$": ResilienceHubResponse.dispatch,
    "{0}/list-app-assessments$": ResilienceHubResponse.dispatch,
    "{0}/list-app-component-compliances$": ResilienceHubResponse.dispatch,
    "{0}/list-app-component-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/list-app-input-sources$": ResilienceHubResponse.dispatch,
    "{0}/list-app-version-app-components$": ResilienceHubResponse.dispatch,
    "{0}/list-app-version-resource-mappings$": ResilienceHubResponse.dispatch,
    "{0}/list-app-version-resources$": ResilienceHubResponse.dispatch,
    "{0}/list-app-versions$": ResilienceHubResponse.dispatch,
    "{0}/list-apps$": ResilienceHubResponse.dispatch,
    "{0}/list-metrics$": ResilienceHubResponse.dispatch,
    "{0}/list-recommendation-templates$": ResilienceHubResponse.dispatch,
    "{0}/list-resiliency-policies$": ResilienceHubResponse.dispatch,
    "{0}/list-resource-grouping-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/list-sop-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/list-suggested-resiliency-policies$": ResilienceHubResponse.dispatch,
    "{0}/list-test-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/list-unsupported-app-version-resources$": ResilienceHubResponse.dispatch,
    "{0}/publish-app-version$": ResilienceHubResponse.dispatch,
    "{0}/put-draft-app-version-template$": ResilienceHubResponse.dispatch,
    "{0}/reject-resource-grouping-recommendations$": ResilienceHubResponse.dispatch,
    "{0}/remove-draft-app-version-resource-mappings$": ResilienceHubResponse.dispatch,
    "{0}/resolve-app-version-resources$": ResilienceHubResponse.dispatch,
    "{0}/start-app-assessment$": ResilienceHubResponse.dispatch,
    "{0}/start-metrics-export$": ResilienceHubResponse.dispatch,
    "{0}/start-resource-grouping-recommendation-task$": ResilienceHubResponse.dispatch,
    "{0}/update-app$": ResilienceHubResponse.dispatch,
    "{0}/update-app-version$": ResilienceHubResponse.dispatch,
    "{0}/update-app-version-app-component$": ResilienceHubResponse.dispatch,
    "{0}/update-app-version-resource$": ResilienceHubResponse.dispatch,
    "{0}/update-resiliency-policy$": ResilienceHubResponse.dispatch,
    "{0}/tags/.+$": ResilienceHubResponse.dispatch,
    "{0}/tags/(?P<arn_prefix>[^/]+)/(?P<workspace_id>[^/]+)$": ResilienceHubResponse.dispatch,
    "{0}/.*$": ResilienceHubResponse.dispatch,
}
