from .responses import GuardDutyResponse

url_bases = [
    "https?://guardduty\\.(.+)\\.amazonaws\\.com",
]


url_paths = {
    "{0}/detector$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/administrator$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/administrator/disassociate$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/admin$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/filter$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/filter/(?P<filter_name>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/ipset$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/ipset/(?P<ip_set_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/threatintelset$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/threatintelset/(?P<threat_intel_set_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/threatentityset$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/threatentityset/(?P<threat_entity_set_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/trustedentityset$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/trustedentityset/(?P<trusted_entity_set_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings/get$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings/statistics$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings/create$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings/archive$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings/unarchive$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/findings/feedback$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/master$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/master/disassociate$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/get$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/delete$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/start$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/stop$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/invite$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/disassociate$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/detector/get$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/member/detector/update$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/freeTrial/daysRemaining$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/usage/statistics$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/malware-scans$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/malware-scan-settings$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/publishingDestination$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/publishingDestination/(?P<destination_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/coverage$": GuardDutyResponse.dispatch,
    "{0}/detector/(?P<detector_id>[^/]+)/coverage/statistics$": GuardDutyResponse.dispatch,
    "{0}/malware-protection-plan$": GuardDutyResponse.dispatch,
    "{0}/malware-protection-plan/(?P<plan_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/malware-scan/(?P<scan_id>[^/]+)$": GuardDutyResponse.dispatch,
    "{0}/malware-scan$": GuardDutyResponse.dispatch,
    "{0}/malware-scan/start$": GuardDutyResponse.dispatch,
    "{0}/object-malware-scan/send$": GuardDutyResponse.dispatch,
    "{0}/invitation$": GuardDutyResponse.dispatch,
    "{0}/invitation/decline$": GuardDutyResponse.dispatch,
    "{0}/invitation/delete$": GuardDutyResponse.dispatch,
    "{0}/invitation/count$": GuardDutyResponse.dispatch,
    "{0}/organization/statistics$": GuardDutyResponse.dispatch,
    "{0}/admin/enable$": GuardDutyResponse.dispatch,
    "{0}/admin/disable$": GuardDutyResponse.dispatch,
    "{0}/admin$": GuardDutyResponse.dispatch,
    "{0}/tags/(?P<resource_arn>.+)$": GuardDutyResponse.dispatch,
}
