from .responses import ResourceAccessManagerResponse

url_bases = [r"https?://ram\.(.+)\.amazonaws.com"]

url_paths = {
    "{0}/acceptresourceshareinvitation$": ResourceAccessManagerResponse.dispatch,
    "{0}/associateresourceshare$": ResourceAccessManagerResponse.dispatch,
    "{0}/associateresourcesharepermission$": ResourceAccessManagerResponse.dispatch,
    "{0}/createpermission$": ResourceAccessManagerResponse.dispatch,
    "{0}/createpermissionversion$": ResourceAccessManagerResponse.dispatch,
    "{0}/createresourceshare$": ResourceAccessManagerResponse.dispatch,
    "{0}/deletepermission$": ResourceAccessManagerResponse.dispatch,
    "{0}/deletepermissionversion$": ResourceAccessManagerResponse.dispatch,
    "{0}/deleteresourceshare/?$": ResourceAccessManagerResponse.dispatch,
    "{0}/disassociateresourceshare$": ResourceAccessManagerResponse.dispatch,
    "{0}/disassociateresourcesharepermission$": ResourceAccessManagerResponse.dispatch,
    "{0}/enablesharingwithawsorganization$": ResourceAccessManagerResponse.dispatch,
    "{0}/getpermission$": ResourceAccessManagerResponse.dispatch,
    "{0}/getresourcepolicies$": ResourceAccessManagerResponse.dispatch,
    "{0}/getresourceshareassociations$": ResourceAccessManagerResponse.dispatch,
    "{0}/getresourceshareinvitations$": ResourceAccessManagerResponse.dispatch,
    "{0}/getresourceshares$": ResourceAccessManagerResponse.dispatch,
    "{0}/listpendinginvitationresources$": ResourceAccessManagerResponse.dispatch,
    "{0}/listpermissionassociations$": ResourceAccessManagerResponse.dispatch,
    "{0}/listpermissions$": ResourceAccessManagerResponse.dispatch,
    "{0}/listpermissionversions$": ResourceAccessManagerResponse.dispatch,
    "{0}/listprincipals$": ResourceAccessManagerResponse.dispatch,
    "{0}/listreplacepermissionassociationswork$": ResourceAccessManagerResponse.dispatch,
    "{0}/listresources$": ResourceAccessManagerResponse.dispatch,
    "{0}/listresourcesharepermissions$": ResourceAccessManagerResponse.dispatch,
    "{0}/listresourcetypes$": ResourceAccessManagerResponse.dispatch,
    "{0}/listsourceassociations$": ResourceAccessManagerResponse.dispatch,
    "{0}/rejectresourceshareinvitation$": ResourceAccessManagerResponse.dispatch,
    "{0}/promotepermissioncreatedfrompolicy$": ResourceAccessManagerResponse.dispatch,
    "{0}/promoteresourcesharecreatedfrompolicy$": ResourceAccessManagerResponse.dispatch,
    "{0}/replacepermissionassociations$": ResourceAccessManagerResponse.dispatch,
    "{0}/setdefaultpermissionversion$": ResourceAccessManagerResponse.dispatch,
    "{0}/tagresource$": ResourceAccessManagerResponse.dispatch,
    "{0}/untagresource$": ResourceAccessManagerResponse.dispatch,
    "{0}/updateresourceshare$": ResourceAccessManagerResponse.dispatch,
}
