"""backup base URL and path."""

from .responses import BackupResponse

url_bases = [
    r"https?://backup\.(.+)\.amazonaws\.com",
]


response = BackupResponse()


url_paths = {
    "{0}/audit/report-plans": response.dispatch,
    "{0}/backup/plans/?$": response.dispatch,
    "{0}/backup/plans/(?P<planId>[^/]+)/?$": response.dispatch,
    "{0}/backup/plans/(?P<planId>[^/]+)/selections/?$": response.dispatch,
    "{0}/backup/plans/(?P<planId>[^/]+)/selections/(?P<selectionId>[^/]+)/?$": response.dispatch,
    "{0}/backup/plans/(?P<planId>[^/]+)/versions/?$": response.dispatch,
    "{0}/backup/plans/(?P<planId>[^/]+)/toTemplate/?$": response.dispatch,
    "{0}/backup/template/plans$": response.dispatch,
    "{0}/backup/template/json/toPlan$": response.dispatch,
    "{0}/backup/template/plans/(?P<templateId>[^/]+)/toPlan$": response.dispatch,
    "{0}/backup-vaults/$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/vault-lock$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/access-policy$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/notification-configuration$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/recovery-points/?$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/recovery-points/(?P<rpArn>[^/]+)/restore-metadata$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/recovery-points/(?P<rpArn>.+)$": response.dispatch,
    "{0}/backup-jobs/?$": response.dispatch,
    "{0}/backup-jobs/(?P<jobId>[^/]+)/?$": response.dispatch,
    "{0}/copy-jobs/?$": response.dispatch,
    "{0}/copy-jobs/(?P<jobId>[^/]+)/?$": response.dispatch,
    "{0}/restore-jobs/?$": response.dispatch,
    "{0}/restore-jobs/(?P<jobId>[^/]+)/metadata$": response.dispatch,
    "{0}/restore-jobs/(?P<jobId>[^/]+)/validations$": response.dispatch,
    "{0}/restore-jobs/(?P<jobId>[^/]+)/?$": response.dispatch,
    "{0}/tags/(?P<resource_arn>.+)$": response.dispatch,
    "{0}/untag/(?P<resource_arn>.+)$": response.dispatch,
    "{0}/audit/report-plans$": BackupResponse.dispatch,
    "{0}/audit/report-plans/(?P<reportPlanName>[^/]+)$": BackupResponse.dispatch,
    "{0}/audit/frameworks/?$": response.dispatch,
    "{0}/audit/frameworks/(?P<frameworkName>[^/]+)/?$": response.dispatch,
    "{0}/global-settings$": response.dispatch,
    "{0}/account-settings$": response.dispatch,
    "{0}/supported-resource-types$": response.dispatch,
    "{0}/legal-holds/?$": response.dispatch,
    "{0}/legal-holds/(?P<holdId>[^/]+)/?$": response.dispatch,
    "{0}/resources/?$": response.dispatch,
    "{0}/resources/(?P<resourceArn>[^/]+)/restore-jobs/?$": response.dispatch,
    "{0}/resources/(?P<resourceArn>[^/]+)/recovery-points/?$": response.dispatch,
    "{0}/resources/(?P<resourceArn>.+)$": response.dispatch,
    "{0}/restore-testing/plans/?$": response.dispatch,
    "{0}/restore-testing/plans/(?P<planName>[^/]+)/?$": response.dispatch,
    "{0}/restore-testing/plans/(?P<planName>[^/]+)/selections/?$": response.dispatch,
    "{0}/restore-testing/plans/(?P<planName>[^/]+)/selections/(?P<selName>[^/]+)/?$": response.dispatch,
    "{0}/logically-air-gapped-backup-vaults/?$": response.dispatch,
    "{0}/logically-air-gapped-backup-vaults/(?P<name>[^/]+)/?$": response.dispatch,
    "{0}/audit/report-jobs/?$": response.dispatch,
    "{0}/audit/report-jobs/(?P<reportJobId>[^/]+)/?$": response.dispatch,
    "{0}/audit/report-plans/(?P<reportPlanName>[^/]+)/jobs/?$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/recovery-points/(?P<rpArn>[^/]+)/disassociate$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/recovery-points/(?P<rpArn>[^/]+)/parentDisassociate$": response.dispatch,
    "{0}/legal-holds/(?P<holdId>[^/]+)/recovery-points/?$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/resources/?$": response.dispatch,
    "{0}/audit/backup-job-summaries/?$": response.dispatch,
    "{0}/audit/copy-job-summaries/?$": response.dispatch,
    "{0}/audit/restore-job-summaries/?$": response.dispatch,
    "{0}/scan/job$": response.dispatch,
    "{0}/scan/jobs/?$": response.dispatch,
    "{0}/scan/jobs/(?P<scan_job_id>[^/]+)/?$": response.dispatch,
    "{0}/tiering-configurations/(?P<tieringConfigurationName>[^/]+)/?$": response.dispatch,
    "{0}/tiering-configurations/?$": response.dispatch,
    "{0}/indexes/recovery-point/?$": response.dispatch,
    "{0}/audit/scan-job-summaries/?$": response.dispatch,
    "{0}/logically-air-gapped-backup-vaults/(?P<name>[^/]+)/restore-access-backup-vaults/?$": response.dispatch,
    "{0}/logically-air-gapped-backup-vaults/(?P<name>[^/]+)/restore-access-backup-vaults/(?P<arn>.+)$": response.dispatch,
    "{0}/restore-testing/inferred-metadata$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/recovery-points/(?P<rpArn>.+)/index/?$": response.dispatch,
    "{0}/backup-vaults/(?P<name>[^/]+)/mpaApprovalTeam.*$": response.dispatch,
    "{0}/restore-access-backup-vaults/?$": response.dispatch,
}
