PAGINATION_MODEL = {
    "list_permission_sets": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "PermissionSets",
        "unique_attribute": "permission_set_arn",
    },
    "list_account_assignments_for_principal": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "AccountAssignments",
        "unique_attribute": [
            "AccountId",
            "PermissionSetArn",
            "PrincipalId",
            "PrincipalType",
        ],
    },
    "list_account_assignments": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "AccountAssignments",
        "unique_attribute": [
            "AccountId",
            "PermissionSetArn",
            "PrincipalId",
            "PrincipalType",
        ],
    },
    "list_managed_policies_in_permission_set": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "AttachedManagedPolicies",
        "unique_attribute": ["arn"],
    },
    "list_customer_managed_policy_references_in_permission_set": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "CustomerManagedPolicyReferences",
        "unique_attribute": ["name", "path"],
    },
    "list_tags_for_resource": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "Tags",
        "unique_attribute": "Key",
    },
    "list_account_assignment_creation_status": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "AccountAssignmentsCreationStatus",
        "unique_attribute": "RequestId",
    },
    "list_account_assignment_deletion_status": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "AccountAssignmentsDeletionStatus",
        "unique_attribute": "RequestId",
    },
    "list_permission_set_provisioning_status": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "PermissionSetsProvisioningStatus",
        "unique_attribute": "RequestId",
    },
    "list_applications": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "Applications",
        "unique_attribute": "application_arn",
    },
    "list_application_access_scopes": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "Scopes",
        "unique_attribute": "Scope",
    },
    "list_application_assignments": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "ApplicationAssignments",
        "unique_attribute": ["application_arn", "principal_type", "principal_id"],
    },
    "list_application_assignments_for_principal": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "ApplicationAssignments",
        "unique_attribute": ["ApplicationArn", "PrincipalType", "PrincipalId"],
    },
    "list_application_authentication_methods": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "AuthenticationMethods",
        "unique_attribute": "AuthenticationMethodType",
    },
    "list_application_grants": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "Grants",
        "unique_attribute": "GrantType",
    },
    "list_trusted_token_issuers": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "TrustedTokenIssuers",
        "unique_attribute": "trusted_token_issuer_arn",
    },
    "list_application_providers": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "ApplicationProviders",
        "unique_attribute": "ApplicationProviderArn",
    },
    "list_regions": {
        "input_token": "next_token",
        "limit_key": "max_results",
        "limit_default": 100,
        "result_key": "Regions",
        "unique_attribute": "Region",
    },
}
