from .responses import GreengrassResponse

url_bases = [
    r"https?://greengrass\.(.+)\.amazonaws.com",
]

url_paths = {
    "{0}/greengrass/definition/cores$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/cores/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/cores/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/cores/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/devices$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/devices/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/devices/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/devices/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/functions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/functions/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/functions/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/functions/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/resources$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/resources/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/resources/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/subscriptions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/subscriptions/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/subscriptions/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/subscriptions/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/resources/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/connectors$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/connectors/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/connectors/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/connectors/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/loggers$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/loggers/(?P<definition_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/loggers/(?P<definition_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/definition/loggers/(?P<definition_id>[^/]+)/versions/(?P<definition_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/role$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/versions$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/deployments$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<GroupId>[^/]+)/deployments/\\$reset$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/deployments/(?P<group_version_id>[^/]+)/status$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/versions/(?P<group_version_id>[^/]+)/?$": GreengrassResponse.dispatch,
    "{0}/greengrass/tags/(?P<resource_arn>.+)$": GreengrassResponse.dispatch,
    "{0}/greengrass/servicerole$": GreengrassResponse.dispatch,
    "{0}/greengrass/bulk/deployments$": GreengrassResponse.dispatch,
    "{0}/greengrass/bulk/deployments/(?P<bulk_deployment_id>[^/]+)/status$": GreengrassResponse.dispatch,
    "{0}/greengrass/bulk/deployments/(?P<bulk_deployment_id>[^/]+)/detailed-reports$": GreengrassResponse.dispatch,
    "{0}/greengrass/things/(?P<thing_name>[^/]+)/connectivityInfo$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/certificateauthorities$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/certificateauthorities/(?P<ca_id>[^/]+)$": GreengrassResponse.dispatch,
    "{0}/greengrass/groups/(?P<group_id>[^/]+)/certificateauthorities/configuration/expiry$": GreengrassResponse.dispatch,
    "{0}/greengrass/updates$": GreengrassResponse.dispatch,
    "{0}/greengrass/things/(?P<thing_name>[^/]+)/runtimeconfig$": GreengrassResponse.dispatch,
}
